### ISSUE TITLE
谷歌的手势识别apk只能在手机端运行吗

### ISSUE THREAD

**Issue by nostayup** [shoutOutYangJie/HandAI#1]
谷歌的手势识别apk只能在手机端运行吗

**Comment by shoutOutYangJie** [comment]
可以在ios端运行 谷歌开放了java代码 你需要永Xcode自己编译。
Sure.google has released java code. You need compile it by yourself using Xcode&nbsp;





------------------ 原始邮件 ------------------
发件人: LiErlong <notifications@github.com&gt;
发送时间: 2020年1月5日 10:19
收件人: shoutOutYangJie/HandAI <HandAI@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[shoutOutYangJie/HandAI] 谷歌的手势识别apk只能在手机端运行吗 (#1)




谷歌的手势识别apk只能在手机端运行吗
