### ISSUE TITLE
想问一下速度方面怎么样呢？

### ISSUE THREAD

**Issue by chenyuqing** [shoutOutYangJie/HandAI#2]
你好，想问一下速度方面怎么样呢？

**Comment by shoutOutYangJie** [comment]
you can find it on README


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tim Chan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 上午8:24
收件人:&nbsp;"shoutOutYangJie/HandAI"<HandAI@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[shoutOutYangJie/HandAI] 想问一下速度方面怎么样呢？ (#2)




你好，想问一下速度方面怎么样呢？
